//
// Copyright 2020 WebAssembly Community Group participants
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//

WASP_V(0x70, Funcref, "funcref")
WASP_FEATURE_V(0x6f, Externref, "externref", reference_types)
WASP_FEATURE_V(0x6e, Anyref, "anyref", gc)
WASP_FEATURE_V(0x6d, Eqref, "eqref", gc)
WASP_FEATURE_V(0x6a, I31ref, "i31ref", gc)
