version: 2.1

commands:
  git:
    description: install git and checkout
    steps:
      - run: |
          apt-get update -q
          apt-get install -q -y git
      - checkout
      - run: git submodule update --init

  install:
    description: install the compiler
    parameters:
      packages:
        type: string
    steps:
      - run: |
          apt-get install -q -y build-essential cmake << parameters.packages >>

  compile:
    description: build the project
    parameters:
      target:
        type: string
    steps:
      - run: make << parameters.target >>

  test:
    description: test the project
    parameters:
      target:
        type: string
    steps:
      - run: make << parameters.target >>

jobs:
  build-gcc-debug:
    docker:
      - image: debian:buster
    steps:
      - git
      - install:
          packages: gcc g++
      - compile:
          target: gcc-debug
      - test:
          target: test-gcc-debug

  build-clang-debug:
    docker:
      - image: debian:buster
    steps:
      - git
      - install:
          packages: clang
      - compile:
          target: clang-debug
      - test:
          target: test-clang-debug

  build-clang-release:
    docker:
      - image: debian:buster
    steps:
      - git
      - install:
          packages: clang
      - compile:
          target: clang-release
      - test:
          target: test-clang-release

workflows:
  version: 2
  build:
    jobs:
      - build-gcc-debug
      - build-clang-debug
      - build-clang-release
